// Title: Durgoroth Town
// File: cave03.c
// Author: Timothy Morris aka Morgoth@Haven
// Date: March 1998
//
// Abstract: Interior of the Durgoroth cave, contains the Saa'HaGoth
//			cleric leader and cleric skill trainer
//
// Revision History: 
//

#include <lib.h>
inherit LIB_ROOM;
#include "../durgoroth.h"

static void create() {
	room::create();
	SetShort("throne room of Morgul");
	SetLong("The center of the large chamber is dominated by the "
		"huge black throne of the legendary Morgul. To each side "
		"are row upon row of free-standing candelabras. Holding "
		"what must be hundreds upon hundreds of lit candles. Yet "
		"the light generated by all the candles seems to be sucked "
		"up by the strangely black form of the throne. To the south "
		"a large ebony arch leads into a passage going south. To the "
		"north a similar arch leads in that direction. An eerie "
		"cold blue glow can be seen beyond it.");
	SetObviousExits("north, south, west");
	SetClimate("indoors");
	SetDomain("FrostMarches");
	SetAmbientLight(25);
	SetItems( ([
		({"large chamber","chamber","cave"}) : (: GetLong :),
		({"throne","huge black throne","morgul's throne",
		"black throne","huge throne"}) : "The massive throne is "
			"formed completely out of a strange smooth black stone. "
			"Blacker then the darkest night. It seems to suck up "
			"all of the light that touches it, leaving a dark void "
			"in the center of the room.",
		({"candelabra","candelabras","candle","candles"}) : "The "
			"edges of the chamber are lined with dozens of solid "
			"gold candelabras holding lit candles.",
		({"southern arch","southern ebony arch","passage"}) :
			"The black stone arch supports a passage running "
			"away to the south.",
		({"northern arch","northern ebony arch","eerie glow",
		"eerie blue glow","cold blue glow","blue glow","glow"}) :
			"The black stone arch supports a passage leading away "
			"to the north. Beyond is an eerie cold blue glow, which "
			"can not be identified.",
		({"ebony arch","arch","arches"}) : "Do you mean the northern "
			"arch or the southern arch?",
		]) );
	SetExits( ([
		"north" : D_ROOM + "/cave04",
		"south" : D_ROOM + "/cave02",
              "west" : D_ROOM + "/cave06",
		]) );
	SetInventory( ([
                D_NPC + "/morgul" : 1,
		]) );
	}
