#define BALZ_DIR "/domains/westwood/areas/enchanted_trees"
#define BALZ_DIR "/domains/westwood/areas/enchanted_trees_needs_re-code"
#define B_OBJ    BALZ_DIR + "/obj"
#define B_NPC    BALZ_DIR + "/npc"
#define B_ROOM   BALZ_DIR + "/room"
